#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'AckMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 5

# The Active Message type associated with this message.
AM_TYPE = 3

class AckMsg(tinyos.message.Message.Message):
    # Create a new AckMsg of size 5.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=5):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <AckMsg> \n"
        try:
            s += "  [node_id=0x%x]\n" % (self.get_node_id())
        except:
            pass
        try:
            s += "  [seq=0x%x]\n" % (self.get_seq())
        except:
            pass
        try:
            s += "  [crc=0x%x]\n" % (self.get_crc())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: node_id
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'node_id' is signed (False).
    #
    def isSigned_node_id(self):
        return False
    
    #
    # Return whether the field 'node_id' is an array (False).
    #
    def isArray_node_id(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'node_id'
    #
    def offset_node_id(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'node_id'
    #
    def offsetBits_node_id(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'node_id'
    #
    def get_node_id(self):
        return self.getUIntElement(self.offsetBits_node_id(), 16, 1)
    
    #
    # Set the value of the field 'node_id'
    #
    def set_node_id(self, value):
        self.setUIntElement(self.offsetBits_node_id(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'node_id'
    #
    def size_node_id(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'node_id'
    #
    def sizeBits_node_id(self):
        return 16
    
    #
    # Accessor methods for field: seq
    #   Field type: short
    #   Offset (bits): 16
    #   Size (bits): 8
    #

    #
    # Return whether the field 'seq' is signed (False).
    #
    def isSigned_seq(self):
        return False
    
    #
    # Return whether the field 'seq' is an array (False).
    #
    def isArray_seq(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'seq'
    #
    def offset_seq(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'seq'
    #
    def offsetBits_seq(self):
        return 16
    
    #
    # Return the value (as a short) of the field 'seq'
    #
    def get_seq(self):
        return self.getUIntElement(self.offsetBits_seq(), 8, 1)
    
    #
    # Set the value of the field 'seq'
    #
    def set_seq(self, value):
        self.setUIntElement(self.offsetBits_seq(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'seq'
    #
    def size_seq(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'seq'
    #
    def sizeBits_seq(self):
        return 8
    
    #
    # Accessor methods for field: crc
    #   Field type: int
    #   Offset (bits): 24
    #   Size (bits): 16
    #

    #
    # Return whether the field 'crc' is signed (False).
    #
    def isSigned_crc(self):
        return False
    
    #
    # Return whether the field 'crc' is an array (False).
    #
    def isArray_crc(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'crc'
    #
    def offset_crc(self):
        return (24 / 8)
    
    #
    # Return the offset (in bits) of the field 'crc'
    #
    def offsetBits_crc(self):
        return 24
    
    #
    # Return the value (as a int) of the field 'crc'
    #
    def get_crc(self):
        return self.getUIntElement(self.offsetBits_crc(), 16, 1)
    
    #
    # Set the value of the field 'crc'
    #
    def set_crc(self, value):
        self.setUIntElement(self.offsetBits_crc(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'crc'
    #
    def size_crc(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'crc'
    #
    def sizeBits_crc(self):
        return 16
    
