 #
 # This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 # This class includes values of some nesC constants from
 # ../Packets.h.
 #/

class Packets:
    SC_D_ADC_3 = 13
    ERR_PACK_STATE_OVERFLOW = 19
    ERR_SEND_TIMEOUT = 3
    RS_ADC_3 = 6
    NODE_TYPE_MAX = 15
    SC_GIO2 = 20
    RS_TSR = 10
    AM_STATEV1MSG = 4
    SC_TEMPERATURE = 0
    RS_GIO3 = 12
    RS_ADC_1 = 4
    AM_ACKMSG = 3
    SC_D_ADC_2 = 11
    RS_ADC_7 = 8
    SC_ADC_1 = 8
    RS_PAR = 9
    RS_VOLTAGE = 2
    SC_PACKED_SIZE = 15
    SC_TSR = 19
    SC_D_ADC_7 = 17
    SC_SIZE = 23
    ERR_SEND_WHILE_SENDING = 11
    SC_ADC_6 = 14
    RS_HUMIDITY = 1
    AM_STATEMSG = 9
    SC_D_ADC_0 = 7
    AM_BOOTMSG = 8
    ERR_SEND_CANCEL_FAIL = 2
    SC_ADC_7 = 16
    ERR_SEND_FAILED = 5
    SC_HUMIDITY = 2
    SC_ADC_2 = 10
    SC_VOLTAGE = 4
    RS_NO_DELTA = 9
    ERR_QUEUE_FULL = 1
    SC_NO_DELTA = 18
    SC_GIO3 = 21
    ERR_SEND_WHILE_PACKET_PENDING = 7
    RS_ADC_0 = 3
    RS_GIO2 = 11
    SC_D_ADC_1 = 9
    AM_STATEV2MSG = 7
    RS_TEMPERATURE = 0
    RS_SIZE = 13
    SPECIAL = 199
    ERR_UART_FAIL = 2
    SC_D_VOLTAGE = 5
    RS_ADC_2 = 5
    ERR_HEARTBEAT = 13
    DIS_SETTINGS = 6
    RS_ADC_6 = 7
    SC_ADC_3 = 12
    SC_D_TEMPERATURE = 1
    ERR_ACK_CRC_CORRUPT = 17
    NODE_TYPE_BASE = 0
    SC_PAR = 18
    AM_CONFIGMSG = 5
    SC_ERRNO = 22
    SC_D_HUMIDITY = 3
    SC_ADC_0 = 6
    SC_D_ADC_6 = 15

