version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ch
      MYSQL_USER: chuser
      MYSQL_PASSWORD: chpass
    volumes:
      - dbdata:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      CH_DBURL: mysql://chuser:chpass@db/ch?connect_timeout=1

volumes:
  dbdata:
