PFLAGS += -I../ -I ../FilterWrapper -I ../../Util

COMPONENT=PredictTestC
CFLAGS += -I$(TOSDIR)/lib/printf -Wall 
CFLAGS += -DPRINTF_BUFFER_SIZE=2048
CFLAGS += -DDEF_SENSE_PERIOD=1L
include $(MAKERULES)

