COMPONENT=TestC
CFLAGS += -I../../../../Util/
CFLAGS += -I.. -I$(TOSDIR)/lib/printf
CFLAGS += -DDEBUG
#CFLAGS += -W -Wall -Wundef -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -O2

include $(MAKERULES)
