PFLAGS += -I../ -I ../../FilterWrapper -I ../../SIPController -I ../../Predict \
	-I../../../Util

COMPONENT=DEWMATestC
CFLAGS += -I$(TOSDIR)/lib/printf -Wall 
CFLAGS += -DPRINTF_BUFFER_SIZE=2048
CFLAGS += -DDEF_SENSE_PERIOD=307200L

include $(MAKERULES)

