type_lookup = {
	    0: "Temperature",
	    1: "D_Temperature",
        2: "Humidity",
        3: "D_Humidity",
        4: "Voltage",
        5: "D_Voltage",
        6: "ADC_0",
        7: "D_ADC_0",
        8: "ADC_1",
        9: "D_ADC_1",
        10: "ADC_2",
        11: "D_ADC_2",
        12: "ADC_3",
        13: "D_ADC_3",
        14: "ADC_6",
        15: "D_ADC_6",
        16: "ADC_7",
        17: "D_ADC_7",
        18: "PAR",
        19: "TSR",
        20: "GIO2",
        21: "GIO3",
        22: "Error",
        23: 'Size"
        }
