type_lookup = {

0: "Temperature",
  1: "D_Temperature",
  2: "Humidity",
  3: "D_Humidity",
  4: "Par",
  5: "Tsr",
  6: "Voltage",
  7: "D_Voltage",
  8: "Co2",
  9: "Aq",
  10: "Voc",
  11: "Power",
  12: "Heat",
  13: "Duty_Time",
  14: "Errno",
  15: "Power_Min",
  16: "Power_Max",
  17: "Power_Kwh",
  18: "Heat_Energy",
  19: "Heat_Volume",
  20: "D_Co2",
  21: "D_Voc",
  22: "D_Aq",
  23: "Wall_Temp",
  24: "D_Wall_Temp",
  25: "Wall_Hum",
  26: "D_Wall_Hum", 
  40: "Opti",
  41: "Tempadc1",
  42: "D_Tempadc1",
  43: "Gas",
  44: "D_Opti",
  45: "Window",
  46: "Bb",
  47: "D_Bb" }

# type_lookup = {
# 	    0: "Temperature",
# 	    1: "D_Temperature",
#         2: "Humidity",
#         3: "D_Humidity",
#         4: "Voltage",
#         5: "D_Voltage",
#         6: "ADC_0",
#         7: "D_ADC_0",
#         8: "ADC_1",
#         9: "D_ADC_1",
#         10: "ADC_2",
#         11: "D_ADC_2",
#         12: "ADC_3",
#         13: "D_ADC_3",
#         14: "ADC_6",
#         15: "D_ADC_6",
#         16: "ADC_7",
#         17: "D_ADC_7",
#         18: "PAR",
#         19: "TSR",
#         20: "GIO2",
#         21: "GIO3",
#         22: "Error",
#         23: "Size"
#         }
