#! /bin/sh
# /etc/init.d/ch-sf

### BEGIN INIT INFO
# Provides:          ch-sf
# Required-Start:    $remote_fs $syslog mysql
# Required-Stop:     $remote_fs $syslog mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Serial Forwarder
# Description:       A simple script from www.stuffaboutcode.com which will start / stop cogent-house at boot / shutdown.
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
    start)
	log_daemon_msg "Starting cogent-house serial forwarder" "ch-sf" || true
	. /opt/tinyos-main-read-only/tinyos.sh>/dev/null

	PORT="/dev/ttyTelos"
	if start-stop-daemon --start --background --make-pidfile --chuid chuser --oknodo --pidfile /var/run/ch-sf.pid --exec /usr/bin/java -- net.tinyos.sf.SerialForwarder -comm serial@$PORT:telosb -no-output; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
    stop)
	log_daemon_msg "Stopping cogent-house serial forwarder" "ch-sf" || true
    # kill application you want to stop
	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/ch-sf.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
    status)
	status_of_proc -p /var/run/ch-sf.pid /usr/bin/java ch-sf && exit 0 || exit $?
	;;
    
    *)
	log_action_msg "Usage: /etc/init.d/ch-sf {start|stop}" || true
	exit 1
	;;
esac

exit 0
