#!/bin/bash

# Wrapper script for RestPusher - attempts to push the ch db every hour includes checks on 3g connectivity

#select random time within 10 mins of call
# ignore output
exec >/dev/null 2>/dev/null
RTIME=`shuf -i 0-600 -n 1`
#sleep $RTIME

SIP="8.8.8.8"
TIMEOUT=30
COUNT=1
while [ $COUNT -lt $TIMEOUT ]
do
    let COUNT++
    if ping -q -c 1 $SIP >/dev/null
    then
	cd /opt/cogent-house/cogent/push && python check-rpc.py
	break #SUCESSS
    fi
    sleep 10
done

