"""Added NodeBoot Table

Revision ID: 1dce0115d073
Revises: 1eba4fe66575
Create Date: 2014-07-22 12:47:31.165119

"""

# revision identifiers, used by Alembic.
revision = '1dce0115d073'
down_revision = '1eba4fe66575'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.create_table('NodeBoot',
    sa.Column('time', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('nodeId', sa.Integer(), nullable=True, primary_key=True),
    sa.Column('clustered', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['nodeId'], ['Node.id'], ),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NodeBoot')
    ### end Alembic commands ###
