"""test

Revision ID: 1e6b75bbade9
Revises: b90c0470e9da
Create Date: 2020-02-18 21:02:08.334697

"""

# revision identifiers, used by Alembic.
revision = '1e6b75bbade9'
down_revision = 'b90c0470e9da'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HouseMetadata')
    op.create_index('pk', 'NodeBoot', ['time', 'nodeId'], unique=False)
    op.create_foreign_key(None, 'NodeLocation', 'Node', ['nodeId'], ['id'])
    op.create_foreign_key(None, 'NodeLocation', 'Location', ['LocationId'], ['id'])
    op.create_index('ns_1', 'NodeState', ['time', 'nodeId', 'localtime'], unique=False)
    op.drop_index('time', table_name='NodeState')
    op.drop_index('time_2', table_name='NodeState')
    op.create_foreign_key(None, 'NodeState', 'Node', ['nodeId'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'NodeState', type_='foreignkey')
    op.create_index('time_2', 'NodeState', ['time', 'nodeId', 'seq_num'], unique=True)
    op.create_index('time', 'NodeState', ['time', 'nodeId', 'seq_num'], unique=True)
    op.drop_index('ns_1', table_name='NodeState')
    op.drop_constraint(None, 'NodeLocation', type_='foreignkey')
    op.drop_constraint(None, 'NodeLocation', type_='foreignkey')
    op.drop_index('pk', table_name='NodeBoot')
    op.create_table('HouseMetadata',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('houseId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('units', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('value', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['houseId'], ['House.id'], name='HouseMetadata_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
