"""populate sensortype nodetype

Revision ID: 25a5ee59d391
Revises: 249f360e32e3
Create Date: 2013-01-15 22:03:46.253985

"""

# revision identifiers, used by Alembic.
revision = '25a5ee59d391'
down_revision = '249f360e32e3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Float


def upgrade():
    sensortype = table('SensorType',
                       column('id', Integer),
                       column('name', String(255)),
                       column('code', String(50)),
                       column('units', String(20)),
                       column('c0', Float),
                       column('c1', Float),
                       column('c2', Float),
                       column('c3', Float))
                       
    op.bulk_insert(sensortype,
                   [{'id': 0, 'name': "Temperature",
                     'code': "T",
                     'units': "deg.C",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 1, 'name': "Delta Temperature",
                     'code': "dT",
                     'units': "deg.C/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 2, 'name': "Humidity",
                     'code': "RH",
                     'units': "%",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 3, 'name': "Delta Humidity",
                     'code': "dRH",
                     'units': "%/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 4, 'name': "Light PAR",
                     'code': "PAR",
                     'units': "Lux",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 5, 'name': "Light TSR",
                     'code': "TSR",
                     'units': "Lux",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 6, 'name': "Battery Voltage",
                     'code': "BAT",
                     'units': "V",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 7, 'name': "Delta Battery Voltage",
                     'code': "dBT",
                     'units': "V/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 8, 'name': "CO2",
                     'code': "CO2",
                     'units': "ppm",
                     
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 9, 'name': "Delta CO2",
                     'code': "AQ",
                     'units': "ppm/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 10, 'name': "Temperature ADC0",
                     'code': "TA0",
                     'units': "deg.C",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 11, 'name': "Delta Temperature ADC0",
                     'code': "DT0",
                     'units': "deg.C/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 12, 'name': "Temperature ADC1",
                     'code': "TA1",
                     'units': "deg.C",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 13, 'name': "Delta Temperature ADC1",
                     'code': "DT1",
                     'units': "deg.C/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 14, 'name': "Temperature ADC2",
                     'code': "TA2",
                     'units': "deg.C",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 15, 'name': "Delta Temperature ADC2",
                     'code': "DT2",
                     'units': "deg.C/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 16, 'name': "Temperature ADC3",
                     'code': "TA3",
                     'units': "deg.C",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 17, 'name': "Delta Temperature ADC3",
                     'code': "DT3",
                     'units': "deg.C/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                     
                     
                    {'id': 18, 'name': "Flow ADC1",
                     'code': "FA1",
                     'units': "m/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 19, 'name': "Delta Flow ADC1",
                     'code': "DF1",
                     'units': "m/s/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 20, 'name': "Flow ADC3",
                     'code': "FA3",
                     'units': "m/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 21, 'name': "Delta Flow ADC3",
                     'code': "DF3",
                     'units': "m/s/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 22, 'name': "Flow ADC7",
                     'code': "FA7",
                     'units': "m/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 23, 'name': "Delta Flow ADC7",
                     'code': "DF7",
                     'units': "m/s/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 24, 'name': "Solar",
                     'code': "SOL",
                     'units': "v",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 25, 'name': "Delta Solar",
                     'code': "DSO",
                     'units': "v/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 26, 'name': "Solar ADC3",
                     'code': "SO3",
                     'units': "v",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 27, 'name': "Delta Solar ADC 3",
                     'code': "DS3",
                     'units': "v/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 28, 'name': "Black Bulb",
                     'code': "BB",
                     'units': "v",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 29, 'name': "Delta Black Bulb",
                     'code': "DBB",
                     'units': "v/s",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 30, 'name': "Duty Cycle",
                     'code': "DUT",
                     'units': "ms",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},
                    {'id': 31, 'name': "Error",
                     'code': "ERR",
                     'units': "E.No",
                     'c0': 0., 'c1': 1., 'c2': 0., 'c3': 0.},])


    pass

def downgrade():
    pass
