"""Move link between server and house to house table to support multiple houses on one server

Revision ID: 29e48346aca2
Revises: 1fcb107574ff
Create Date: 2014-02-19 12:24:05.253807

"""

# revision identifiers, used by Alembic.
revision = '29e48346aca2'
down_revision = '1fcb107574ff'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Server_ibfk_2','Server','foreignkey')
    op.drop_column('Server', 'houseid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Server', sa.Column('houseid', mysql.INTEGER(display_width=11), nullable=True))
    ### end Alembic commands ###
