"""Add Link between server and house to house table

Revision ID: 2b40fc51f91e
Revises: 29e48346aca2
Create Date: 2014-02-19 12:53:21.644673

"""

# revision identifiers, used by Alembic.
revision = '2b40fc51f91e'
down_revision = '29e48346aca2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('House', sa.Column('serverid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('House', 'serverid')
    ### end Alembic commands ###
