"""location

Revision ID: 31851b4865f1
Revises: 4a90237e5674
Create Date: 2012-02-07 19:01:16.480068

"""

# revision identifiers, used by Alembic.
revision = '31851b4865f1'
down_revision = '4a90237e5674'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from sqlalchemy.sql import table, column, text
from sqlalchemy import Integer, String, ForeignKey, DateTime, Float, Boolean, UniqueConstraint


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(text('ALTER TABLE House ENGINE=INNODB;'))
    op.execute(text('ALTER TABLE Room ENGINE=INNODB;'))
    op.create_table('Location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('houseId', sa.Integer(), nullable=True),
    sa.Column('roomId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['houseId'], ['House.id'], ),
    sa.ForeignKeyConstraint(['roomId'], ['Room.id'], ),
    )
    op.add_column(u'Node', sa.Column('locationId', sa.Integer(), nullable=True))
    # generate location table from current node locations
    op.execute(text("insert into Location (houseId, roomId) select distinct houseId, roomId from Node where houseId is not null and roomId is not Null;"))
    # update Node locations
    op.execute(text("update Node join Location on Node.houseId = Location.houseId and Node.roomId = Location.roomId set Node.locationId = Location.id;"))
    op.add_column(u'Reading', sa.Column('locationId', sa.Integer(), nullable=True))
    # fill old readings from current node location
    op.execute(text("""UPDATE Reading JOIN Node ON Reading.nodeId = Node.id
                       SET Reading.locationId = Node.locationId;"""))
    op.drop_column(u'Node', u'roomId')
    op.drop_column(u'Node', u'houseId')
    op.drop_column(u'Reading', u'id')
    op.alter_column(u'Reading', u'type', 
               existing_type=mysql.INTEGER(display_width=11), 
               nullable=False)
    op.alter_column(u'Reading', u'nodeId', 
               existing_type=mysql.INTEGER(display_width=11), 
               nullable=False)
    op.alter_column(u'Reading', u'time', 
               existing_type=sa.DATETIME(), 
               nullable=False)
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # put back into node the room and house ids
    
    op.add_column(u'Node', sa.Column(u'roomId', mysql.INTEGER(display_width=11), nullable=True))
    op.add_column(u'Node', sa.Column(u'houseId', mysql.INTEGER(display_width=11), nullable=True))
    op.execute(text("update Node join Location on Node.locationId = Location.id set Node.houseId = Location.houseId, Node.roomId = Location.roomId;"))

    op.drop_column(u'Node', 'locationId')

    op.add_column(u'Reading', sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False))
    op.alter_column(u'Reading', u'type', 
               existing_type=mysql.INTEGER(display_width=11), 
               nullable=True)
    op.alter_column(u'Reading', u'nodeId', 
               existing_type=mysql.INTEGER(display_width=11), 
               nullable=True)
    op.alter_column(u'Reading', u'time', 
               existing_type=sa.DATETIME(), 
               nullable=True)
    op.drop_column(u'Reading', 'locationId')
    op.drop_table('Location')
    ### end Alembic commands ###
