"""push script

Revision ID: 406589edcb82
Revises: 31851b4865f1
Create Date: 2012-03-26 15:28:12.138519

"""

# revision identifiers, used by Alembic.
revision = '406589edcb82'
down_revision = '31851b4865f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RawMessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('pickedObject', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UploadURL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('dburl', sa.String(length=100), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Host')
    op.drop_table('RawMessage')
    op.drop_table('UploadURL')
    ### end Alembic commands ###
