"""original

Revision ID: 4a90237e5674
Revises: None
Create Date: 2012-02-07 14:22:54.298813

"""

# revision identifiers, used by Alembic.
revision = '4a90237e5674'
#down_revision = '13037206f335'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LastReport',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LastReport')
    ### end Alembic commands ###
