COMPONENT=EchoSerialAppC
CFLAGS += -I$(TOSDIR)/lib/printf -I..
#CFLAGS += -W -Wall -Wundef -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -O2
CFLAGS += -DPRINT_BUFFER_SIZE=2000

include $(MAKERULES)
