COMPONENT=PulseReaderTestC
PFLAGS += -I../../../Util/
CFLAGS += -I$(TOSDIR)/lib/printf
ifdef debug
CFLAGS += -DDEBUG
endif
#CFLAGS += -W -Wall -Wundef -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -O2

include $(MAKERULES)
