PFLAGS += -I../ -I ../../FilterWrapper\
	-I ../../SIPController\
	-I../../../Util

COMPONENT=PassTestC
CFLAGS += -I$(TOSDIR)/lib/printf -Wall 
CFLAGS += -DRS_SIZE=10
CFLAGS += -DPRINTF_BUFFER_SIZE=2048
CFLAGS += -DDEF_SENSE_PERIOD=307200L

include $(MAKERULES)

