COMPONENT=SwitchedAnalogTestC
PFLAGS += -I %T/lib/printf \
	-I ../Analog \
	-I ../GIOSwitch \
	-I ../../../Util


#CFLAGS += -DDEBUG

TINYOS_ROOT_DIR?=/opt/tinyos-main
include $(TINYOS_ROOT_DIR)/Makefile.include
