PFLAGS += -I . -I ../BNController -I ../../Util
COMPONENT=LowBatteryTestC
CFLAGS += -I$(TOSDIR)/lib/printf -Wall 
CFLAGS += -DPRINTF_BUFFER_SIZE=2048
CFLAGS += -DLOW_VOLTAGE=2.35
include $(MAKERULES)





