"""Remove Id from nodestate, new primary key on nodeid, time and seq_num

Revision ID: 1a04848f8857
Revises: 2b40fc51f91e
Create Date: 2014-02-19 12:57:36.472580

"""

# revision identifiers, used by Alembic.
revision = '1a04848f8857'
down_revision = '2b40fc51f91e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    
    #Remove any duplicates
    op.execute("alter ignore table NodeState add unique index(time,nodeId,seq_num);")
    op.drop_column('NodeState', 'id')
    op.alter_column('NodeState', 'nodeId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('NodeState', 'seq_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('NodeState', 'time',
               existing_type=sa.DATETIME(),
               nullable=False)
    #op.create_index('ix_NodeState_nodeId', 'NodeState', ['nodeId'], unique=False)
    op.create_index('ix_NodeState_seq_num', 'NodeState', ['seq_num'], unique=False)
    op.create_index('ix_NodeState_time', 'NodeState', ['time'], unique=False)
    op.create_primary_key(None, "NodeState", ["nodeid","time","seq_num"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE NodeState DROP PRIMARY KEY;")
    op.drop_index('ix_NodeState_time', table_name='NodeState')
    op.drop_index('ix_NodeState_seq_num', table_name='NodeState')
    #op.drop_index('ix_NodeState_nodeId', table_name='NodeState')
    op.alter_column('NodeState', 'time',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('NodeState', 'seq_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('NodeState', 'nodeId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    #Fuck this
    #op.add_column('NodeState', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    #op.create_primary_key(None, "NodeState", ["id"]) #Doesnt work complains about multiple PK's
    op.execute("ALTER TABLE NodeState ADD COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY")

    ### end Alembic commands ###
