"""Added Server Table

Revision ID: 1eba4fe66575
Revises: 303009329387
Create Date: 2014-01-14 11:34:19.721572

"""

# revision identifiers, used by Alembic.
revision = '1eba4fe66575'
down_revision = '303009329387'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('baseid', sa.Integer(), nullable=True),
    sa.Column('houseid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baseid'], ['Node.id'], ),
    sa.ForeignKeyConstraint(['houseid'], ['House.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Server')
    ### end Alembic commands ###
